### ISSUE TITLE
Make fails with various errors

### ISSUE THREAD

**Issue by jamesmkrieger** [BioPP/bpp-phyl#16]
I already installed bpp-core, bpp-seq and bpp-popgen in $bpp_dir then tried bpp-phyl and got the following result:

[jkrieger@cygnus sources]$ cd bpp-phyl/
[jkrieger@cygnus bpp-phyl]$ cmake -DCMAKE_INSTALL_PREFIX=$bpp_dir .
-- The CXX compiler identification is GNU 4.9.4
-- Check for working CXX compiler: /home/jkrieger/programs/gcc-4.9.4-install/bin/c++
-- Check for working CXX compiler: /home/jkrieger/programs/gcc-4.9.4-install/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- bpp-core 3.0.0 found:
--   static lib: /home/jkrieger/Documents/code/bpp/lib64/libbpp-core.a
--   shared lib: /home/jkrieger/Documents/code/bpp/lib64/libbpp-core.so.3.0.0
--   includes: /home/jkrieger/Documents/code/bpp/include
-- bpp-seq 11.0.0 found:
--   static lib: /home/jkrieger/Documents/code/bpp/lib64/libbpp-seq.a
--   shared lib: /home/jkrieger/Documents/code/bpp/lib64/libbpp-seq.so.11.0.0
--   includes: /home/jkrieger/Documents/code/bpp/include
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.5") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jkrieger/Documents/code/bpp/sources/bpp-phyl
[jkrieger@cygnus bpp-phyl]$ make
Scanning dependencies of target bpp-phyl-shared
[  0%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/App/PhylogeneticsApplicationTools.cpp.o
[  0%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/BipartitionList.cpp.o
[  0%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/BipartitionTools.cpp.o
[  1%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Distance/AbstractAgglomerativeDistanceMethod.cpp.o
[  1%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Distance/BioNJ.cpp.o
[  1%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Distance/DistanceEstimation.cpp.o
[  2%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Distance/HierarchicalClustering.cpp.o
[  2%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Distance/NeighborJoining.cpp.o
[  2%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Distance/PGMA.cpp.o
[  2%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Graphics/AbstractDendrogramPlot.cpp.o
[  3%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Graphics/AbstractTreeDrawing.cpp.o
[  3%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Graphics/CladogramPlot.cpp.o
[  3%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Graphics/PhylogramPlot.cpp.o
[  4%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Graphics/TreeDrawingDisplayControler.cpp.o
[  4%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Graphics/TreeDrawingListener.cpp.o
[  4%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Io/BppOFrequenciesSetFormat.cpp.o
[  4%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Io/BppOMultiTreeReaderFormat.cpp.o
[  5%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Io/BppOMultiTreeWriterFormat.cpp.o
[  5%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Io/BppORateDistributionFormat.cpp.o
[  5%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Io/BppOSubstitutionModelFormat.cpp.o
[  6%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Io/BppOTransitionModelFormat.cpp.o
[  6%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Io/BppOTreeReaderFormat.cpp.o
[  6%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Io/BppOTreeWriterFormat.cpp.o
[  7%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Io/IoDistanceMatrixFactory.cpp.o
[  7%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Io/IoFrequenciesSetFactory.cpp.o
[  7%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Io/IoPairedSiteLikelihoods.cpp.o
[  7%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Io/IoSubstitutionModelFactory.cpp.o
[  8%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Io/IoTreeFactory.cpp.o
[  8%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Io/Newick.cpp.o
[  8%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Io/NexusIoTree.cpp.o
[  9%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Io/Nhx.cpp.o
[  9%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Io/PhylipDistanceMatrixFormat.cpp.o
[  9%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Likelihood/AbstractDiscreteRatesAcrossSitesTreeLikelihood.cpp.o
[  9%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Likelihood/AbstractHomogeneousTreeLikelihood.cpp.o
[ 10%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Likelihood/AbstractNonHomogeneousTreeLikelihood.cpp.o
[ 10%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Likelihood/AbstractTreeLikelihood.cpp.o
[ 10%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Likelihood/DRASDRTreeLikelihoodData.cpp.o
[ 11%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Likelihood/DRASRTreeLikelihoodData.cpp.o
[ 11%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Likelihood/DRHomogeneousMixedTreeLikelihood.cpp.o
[ 11%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Likelihood/DRHomogeneousTreeLikelihood.cpp.o
[ 11%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Likelihood/DRNonHomogeneousTreeLikelihood.cpp.o
[ 12%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Likelihood/DRTreeLikelihoodTools.cpp.o
[ 12%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Likelihood/GlobalClockTreeLikelihoodFunctionWrapper.cpp.o
[ 12%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Likelihood/MarginalAncestralStateReconstruction.cpp.o
[ 13%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Likelihood/NNIHomogeneousTreeLikelihood.cpp.o
[ 13%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Likelihood/PairedSiteLikelihoods.cpp.o
[ 13%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Likelihood/PseudoNewtonOptimizer.cpp.o
[ 14%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Likelihood/RASTools.cpp.o
[ 14%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Likelihood/RHomogeneousClockTreeLikelihood.cpp.o
[ 14%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Likelihood/RHomogeneousMixedTreeLikelihood.cpp.o
[ 14%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Likelihood/RHomogeneousTreeLikelihood.cpp.o
[ 15%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Likelihood/RNonHomogeneousMixedTreeLikelihood.cpp.o
[ 15%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Likelihood/RNonHomogeneousTreeLikelihood.cpp.o
[ 15%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Likelihood/TreeLikelihoodTools.cpp.o
[ 16%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Mapping/DecompositionMethods.cpp.o
[ 16%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Mapping/DecompositionReward.cpp.o
[ 16%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Mapping/DecompositionSubstitutionCount.cpp.o
[ 16%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Mapping/LaplaceSubstitutionCount.cpp.o
[ 17%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Mapping/NaiveSubstitutionCount.cpp.o
[ 17%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Mapping/OneJumpSubstitutionCount.cpp.o
[ 17%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Mapping/ProbabilisticRewardMapping.cpp.o
[ 18%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Mapping/ProbabilisticSubstitutionMapping.cpp.o
[ 18%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Mapping/RewardMappingTools.cpp.o
[ 18%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Mapping/SubstitutionMappingTools.cpp.o
[ 19%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Mapping/SubstitutionRegister.cpp.o
[ 19%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Mapping/UniformizationSubstitutionCount.cpp.o
[ 19%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Mapping/WeightedSubstitutionCount.cpp.o
[ 19%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Model/AbstractBiblioMixedSubstitutionModel.cpp.o
[ 20%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Model/AbstractBiblioSubstitutionModel.cpp.o
[ 20%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Model/AbstractFromSubstitutionModelTransitionModel.cpp.o
[ 20%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Model/AbstractKroneckerWordSubstitutionModel.cpp.o
[ 21%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Model/AbstractMixedSubstitutionModel.cpp.o
[ 21%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Model/AbstractSubstitutionModel.cpp.o
[ 21%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Model/AbstractWordSubstitutionModel.cpp.o
[ 21%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Model/BinarySubstitutionModel.cpp.o
[ 22%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Model/Codon/AbstractCodonCpGSubstitutionModel.cpp.o
[ 22%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Model/Codon/AbstractCodonDistanceSubstitutionModel.cpp.o
[ 22%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Model/Codon/AbstractCodonFitnessSubstitutionModel.cpp.o
[ 23%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Model/Codon/AbstractCodonFrequenciesSubstitutionModel.cpp.o
[ 23%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Model/Codon/AbstractCodonPhaseFrequenciesSubstitutionModel.cpp.o
[ 23%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Model/Codon/AbstractCodonSubstitutionModel.cpp.o
/home/jkrieger/Documents/code/bpp/sources/bpp-phyl/src/Bpp/Phyl/Model/Codon/AbstractCodonSubstitutionModel.cpp: In constructor ‘bpp::AbstractCodonSubstitutionModel::AbstractCodonSubstitutionModel(const bpp::GeneticCode*, bpp::NucleotideSubstitutionModel*, bpp::NucleotideSubstitutionModel*, bpp::NucleotideSubstitutionModel*, const string&, bool)’:
/home/jkrieger/Documents/code/bpp/sources/bpp-phyl/src/Bpp/Phyl/Model/Codon/AbstractCodonSubstitutionModel.cpp:87:1: internal compiler error: in possible_polymorphic_call_targets, at ipa-devirt.c:1557
 AbstractCodonSubstitutionModel::AbstractCodonSubstitutionModel(
 ^
0x81e57b possible_polymorphic_call_targets(tree_node*, long, ipa_polymorphic_call_context, bool*, void**, int*)
	/home/jkrieger/old_dir/jkrieger/programs/gcc-4.9.4-src/gcc/ipa-devirt.c:1557
0x7f1641 possible_polymorphic_call_targets
	/home/jkrieger/old_dir/jkrieger/programs/gcc-4.9.4-src/gcc/ipa-utils.h:142
0x7f1641 gimple_fold_call
	/home/jkrieger/old_dir/jkrieger/programs/gcc-4.9.4-src/gcc/gimple-fold.c:1127
0x7f1641 fold_stmt_1
	/home/jkrieger/old_dir/jkrieger/programs/gcc-4.9.4-src/gcc/gimple-fold.c:1302
0xa6e0ba substitute_and_fold(tree_node* (*)(tree_node*), bool (*)(gimple_stmt_iterator*), bool)
	/home/jkrieger/old_dir/jkrieger/programs/gcc-4.9.4-src/gcc/tree-ssa-propagate.c:1200
0xa0ff98 fini_copy_prop
	/home/jkrieger/old_dir/jkrieger/programs/gcc-4.9.4-src/gcc/tree-ssa-copy.c:587
0xa0ff98 execute_copy_prop
	/home/jkrieger/old_dir/jkrieger/programs/gcc-4.9.4-src/gcc/tree-ssa-copy.c:631
0xa0ff98 execute
	/home/jkrieger/old_dir/jkrieger/programs/gcc-4.9.4-src/gcc/tree-ssa-copy.c:669
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <http://gcc.gnu.org/bugs.html> for instructions.
make[2]: *** [src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/Model/Codon/AbstractCodonSubstitutionModel.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/bpp-phyl-shared.dir/all] Error 2
make: *** [all] Error 2

**Comment by jamesmkrieger** [comment]
I forgot to mention my operating system is CentOS 7

**Comment by jydu** [comment]
Hi,

Sorry, but this is difficult to solve, as I cannot reproduce the issue. Also seem rather specific as it looks like a compiler bug rather than an issue with the libraries. Maybe an upgrade of the compiler would help?

J.

**Comment by i-mtz** [comment]
@jydu  I can confirm that the issue seems related to gcc 4.9, as the same error happens in debian 8 with gcc 4.9.2. I was able to successfully compile with  gcc 4.8.4 works (I haven't tried with more recent gcc versions).

**Comment by jydu** [comment]
Strange. At least works with GCC 5, 6 and 7 (Debian Testing).

**Comment by i-mtz** [comment]
gcc 4.9 is not supported anymore by the gcc team, so it should be safe to ignore this if it works with newer versions.
Maybe add a disclaimer or note in the README or INSTALL docs? (just an idea)
