### ISSUE TITLE
error while compiling

### ISSUE THREAD

**Issue by WandrilleD** [BioPP/bpp-phyl#32]
Dear bpp dev team,

I tried following the instructions given there : http://biopp.univ-montp2.fr/wiki/index.php/Installation#Compiling_and_installing

however I got the following error while compiling bpp-phyl:

(base) wandrille@wandrille-Latitude-7400:~/Installed_software/bpp-phyl/build$ cmake -DCMAKE_INSTALL_PREFIX=$bpp_dir .. # prepare compilation
-- The CXX compiler identification is GNU 7.5.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- bpp-core 4.1.0 found:
--   static lib: /lib/libbpp-core.a
--   shared lib: /lib/libbpp-core.so.4.1.0
--   includes: /include
-- bpp-seq 12.0.0 found:
--   static lib: /lib/libbpp-seq.a
--   shared lib: /lib/libbpp-seq.so.12.0.0
--   includes: /include
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/wandrille/Installed_software/bpp-phyl/build
(base) wandrille@wandrille-Latitude-7400:~/Installed_software/bpp-phyl/build$ make # compile
Scanning dependencies of target bpp-phyl-shared
[  0%] Building CXX object src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/App/PhylogeneticsApplicationTools.cpp.o
/home/wandrille/Installed_software/bpp-phyl/src/Bpp/Phyl/App/PhylogeneticsApplicationTools.cpp: In static member function ‘static bpp::TreeLikelihood* bpp::PhylogeneticsApplicationTools::optimizeParameters(bpp::TreeLikelihood*, const bpp::ParameterList&, std::map<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >&, const string&, bool, bool, int)’:
/home/wandrille/Installed_software/bpp-phyl/src/Bpp/Phyl/App/PhylogeneticsApplicationTools.cpp:922:62: error: no matching function for call to ‘bpp::Parameter::setConstraint(bpp::Constraint*, bool)’
           par.setConstraint(ic & (*par.getConstraint()), true);
                                                              ^
In file included from /include/Bpp/Numeric/ParameterList.h:43:0,
                 from /include/Bpp/Numeric/Function/Functions.h:43,
                 from /include/Bpp/Numeric/NumTools.h:43,
                 from /include/Bpp/Numeric/VectorTools.h:44,
                 from /home/wandrille/Installed_software/bpp-phyl/src/Bpp/Phyl/App/../Model/FrequenciesSet/../StateMap.h:46,
                 from /home/wandrille/Installed_software/bpp-phyl/src/Bpp/Phyl/App/../Model/FrequenciesSet/FrequenciesSet.h:44,
                 from /home/wandrille/Installed_software/bpp-phyl/src/Bpp/Phyl/App/../Model/SubstitutionModel.h:43,
                 from /home/wandrille/Installed_software/bpp-phyl/src/Bpp/Phyl/App/PhylogeneticsApplicationTools.h:45,
                 from /home/wandrille/Installed_software/bpp-phyl/src/Bpp/Phyl/App/PhylogeneticsApplicationTools.cpp:41:
/include/Bpp/Numeric/Parameter.h:269:18: note: candidate: virtual void bpp::Parameter::setConstraint(std::shared_ptr<bpp::Constraint>)
     virtual void setConstraint(std::shared_ptr<Constraint> constraint);
                  ^~~~~~~~~~~~~
/include/Bpp/Numeric/Parameter.h:269:18: note:   candidate expects 1 argument, 2 provided
/home/wandrille/Installed_software/bpp-phyl/src/Bpp/Phyl/App/PhylogeneticsApplicationTools.cpp:927:45: error: no matching function for call to ‘bpp::Parameter::setConstraint(bpp::IntervalConstraint*, bool)’
           par.setConstraint(ic.clone(), true);
                                             ^
In file included from /include/Bpp/Numeric/ParameterList.h:43:0,
                 from /include/Bpp/Numeric/Function/Functions.h:43,
                 from /include/Bpp/Numeric/NumTools.h:43,
                 from /include/Bpp/Numeric/VectorTools.h:44,
                 from /home/wandrille/Installed_software/bpp-phyl/src/Bpp/Phyl/App/../Model/FrequenciesSet/../StateMap.h:46,
                 from /home/wandrille/Installed_software/bpp-phyl/src/Bpp/Phyl/App/../Model/FrequenciesSet/FrequenciesSet.h:44,
                 from /home/wandrille/Installed_software/bpp-phyl/src/Bpp/Phyl/App/../Model/SubstitutionModel.h:43,
                 from /home/wandrille/Installed_software/bpp-phyl/src/Bpp/Phyl/App/PhylogeneticsApplicationTools.h:45,
                 from /home/wandrille/Installed_software/bpp-phyl/src/Bpp/Phyl/App/PhylogeneticsApplicationTools.cpp:41:
/include/Bpp/Numeric/Parameter.h:269:18: note: candidate: virtual void bpp::Parameter::setConstraint(std::shared_ptr<bpp::Constraint>)
     virtual void setConstraint(std::shared_ptr<Constraint> constraint);
                  ^~~~~~~~~~~~~
/include/Bpp/Numeric/Parameter.h:269:18: note:   candidate expects 1 argument, 2 provided
/home/wandrille/Installed_software/bpp-phyl/src/Bpp/Phyl/App/PhylogeneticsApplicationTools.cpp: In static member function ‘static void bpp::PhylogeneticsApplicationTools::checkEstimatedParameters(const bpp::ParameterList&)’:
/home/wandrille/Installed_software/bpp-phyl/src/Bpp/Phyl/App/PhylogeneticsApplicationTools.cpp:1388:56: error: cannot convert ‘const std::shared_ptr<bpp::Constraint>’ to ‘const bpp::Constraint*’ in initialization
     const Constraint* constraint = pl[i].getConstraint();
                                                        ^
src/CMakeFiles/bpp-phyl-shared.dir/build.make:62: recipe for target 'src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/App/PhylogeneticsApplicationTools.cpp.o' failed
make[2]: *** [src/CMakeFiles/bpp-phyl-shared.dir/Bpp/Phyl/App/PhylogeneticsApplicationTools.cpp.o] Error 1
CMakeFiles/Makefile2:1047: recipe for target 'src/CMakeFiles/bpp-phyl-shared.dir/all' failed
make[1]: *** [src/CMakeFiles/bpp-phyl-shared.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

don't hesitate to if you need more info to diagnose the problem.

bon courage.

**Comment by jydu** [comment]
Hi,

We are preparing the next version, and the master branches are currently in an unstable state as we are merging the development branches. You can solve the issue by going a few commit back in bpp-core, this should hopefuly allows the other libraries to compile again. We hope to solve this soon!

Cheers,

Julien.

**Comment by alexmcmenamin** [comment]
> Hi,
> 
> We are preparing the next version, and the master branches are currently in an unstable state as we are merging the development branches. You can solve the issue by going a few commit back in bpp-core, this should hopefuly allows the other libraries to compile again. We hope to solve this soon!
> 
> Cheers,
> 
> Julien.

Hi Julien,

I had the same issue. I went back a few commit in bpp-core (simply went back to an earlier commit, downloaded and compiled bpp-core) and still got the same error when I tried to make the bpp-phyl files.

**Comment by jydu** [comment]
Strange, going back to commit df2daf3b70ebd74d1b4d9c318d8db938228a349a in bpp-core (From March 1st, only 2 commits ago) solves the issue for me:

```bash
git clone git@github.com:BioPP/bpp-core.git
git checkout df2daf3b70ebd74d1b4d9c318d8db938228a349a
```
then cmake and make. Can you give it a try and see whether the problem persists?

**Comment by alexmcmenamin** [comment]
That worked! Thanks!

**Comment by jydu** [comment]
This should be fixed now, the master branch can compile again. Be aware, however, that the next version will introduce a few interface breaks. Do not hesitate to post any question you may have!

Julien.
