### ISSUE TITLE
Large RNA virus genomes

### ISSUE THREAD

**Issue by MouthOfUberMadness** [BioPP/bpp-phyl#47]
Hello,

I'm looking at RNA virus genomes. I tried to build a tree with a set of aligned sequences. The issue is that the distance estimation basically never end.

Is there a size limit for these methods to work correctly ?

I use the full genome of these ARN virus (that have I think roughly 30k nucleotides).

Best,

![image](https://user-images.githubusercontent.com/94635330/142473577-14e99301-464a-408b-897e-fc083cc19e0f.png)

**Comment by MouthOfUberMadness** [comment]
Hi,

So this is the piece of code I used. There are 4 sequences.

Best,

MoUM

![image](https://user-images.githubusercontent.com/94635330/142588695-5986dc10-f732-4399-b4a8-4fae364d05aa.png)

**Comment by MouthOfUberMadness** [comment]
Ha, using the LysozymeLarge.fast, and introducing gaps ('-') it produces the same issue.

**Comment by MouthOfUberMadness** [comment]
I replaced all ('-') by ('n') is it a legit transformation in the sense that all substitutions models have a meta layer that allows modeling of the gaps as ('n') virtual nucleotides ?

**Comment by jydu** [comment]
I will give it a closer look. May I just ask which version of Bio++ you are using and how you installed it? I would also recommend adding two file output streams for the profiler and messenger (the two null pointers before the verbose argument).
This will be helpful for debugging, notably to check whether there might be infinite likelihood values.

**Comment by MouthOfUberMadness** [comment]
I use the version coming from a vanilla github checkout. 

But as I said it seems that the pipeline do not handle gaps as '-'. I've seen in one of the example that use RNA strands replace all gaps by unknown characters.

What I'm not sure of is if doing this replacement is actually legit, and is there some documentation that says what are the probabilities transition for this virtual nucleotide.

Otherwise it seems to work.

![image](https://user-images.githubusercontent.com/94635330/142600363-b26ce8dd-a62d-4196-a733-26f8ff3069a6.png)

**Comment by MouthOfUberMadness** [comment]
The current code I use (updated from previous comment), and that seems to work.

![image](https://user-images.githubusercontent.com/94635330/142600620-ec0d452f-47e8-4e9c-bc66-345bdda5aec9.png)

**Comment by jydu** [comment]
Indeed, gaps can only be handled with an appropriate model or replaced by N, the latter being usually the preferred option.

**Comment by MouthOfUberMadness** [comment]
Ok. But I still have a hard time to find (in the documentation) what is the model for these unknown nucleotides. Any ideas ?

**Comment by jydu** [comment]
Yes, it is the model of Rivas and Eddy http://biopp.univ-montp2.fr/apidoc/bpp-phyl/html/classbpp_1_1RE08.html
Note that this model was initially developed for ML inference, with an updated Felsenstein recursion (which is not implemented in Bio++). Nothing prevents you from using it in the context of pairwise likelihoods (distance estimation), however, and it would be very interesting to see how it performs.

**Comment by MouthOfUberMadness** [comment]
Awsome ! 

The thing is the RH08 ask for a bpp::NucleotideReversibleSubstitutionModel typed input. But I only see models that inherits from bpp::AbstractReversibleNucleotideSubstitutionModel. 

So the cast fail for the T92 model for instance.

You're gonna start to hate me with my noob questions...

![image](https://user-images.githubusercontent.com/94635330/142631873-24a858a1-dece-48ee-91c4-a54140213af0.png)

**Comment by jydu** [comment]
Hum, there is indeed something fishy here, as T92 does not inherit from NucleotideReversibleSubstitutionModel... @lgueguen any idea?

**Comment by lgueguen** [comment]
Hi,

yes indeed, it inherits from ReversibleSM & NucleotideSM, but not from RevNuclSM. I check this.

Cheers,
Laurent

**Comment by lgueguen** [comment]
It's fixed.
L

**Comment by jydu** [comment]
@MouthOfUberMadness : there was indeed a bug here which is now fixed. But the fix has been made on the master branch of the repository, which is now set to version 3. V3 introduces several interface breaks, as it features a completely new likelihood framework. You may give it a try, but otherwise, you may just stay with the gap-as-missing behaviour, which is a more common approach. In case you go for updating your code to V3, do not hesitate to report any issue you may encounter.

**Comment by MouthOfUberMadness** [comment]
Nice! I'll try if I can make it work.
Amazed by the quick response and action BTW.

**Comment by MouthOfUberMadness** [comment]
Hello, again.

Not sure if it is the right place to ask for that. I'm trying to understand if a pattern of nucleotides can disappear/appear inside set of RNA strands. I have a dataset that represent the subspace of RNAs I'm working on. 

From what I understood, one can compute the tree that maximize the likelihood of its appearance given the nucleotides transition matrix. 

This allows to "extend" or "simulate" an optimized phylogenetic tree.

Am I wrong when I'm saying that this simulation do not take into account the specific patterns that can show-up in the data such as locations in the strands that are less prone to mutation due to evolutionary disadvantage (I'm thinking of locations that are so crucial for the fitness of the organism that any change here would never stick in the evolutionary process) ?

If I'm right, is there a way to do that with the methods and tools in your library ?

**Comment by lgueguen** [comment]
Hello, 

with bpp-phyl you can simulate the evolution of sequences, including RNA, with many different models, such as site-specific models and rates of evolution. I do not know if it is what you mean. However, all this process is done considering the
usual fact that sites are independent, which is very restrictive. 
To make evolution more realistic, we can simulate the evolution of words, but the number of states increases exponentially with the length of the considered words, and all words are also considered as independent.

I do not know if this replies to you question? 

Cheers,
Laurent
