### ISSUE TITLE
"error: use of deleted function" while install bpp-phyl

### ISSUE THREAD

**Issue by jiee1993** [BioPP/bpp-phyl#48]
Hi,
  I have this problem in `CentOS release 6.5 (Final)` followed your install instructions( `libbpp-core` and `libbpp-seq` installed in turn, and `Eigen3 (version 3.4.0)` installed).

**Firstly cmake Compiling with:**
    `cmake ../bpp-phyl-master/ -DCMAKE_INSTALL_PREFIX=/data1/bio-soft/BioPP/bin/ -DBUILD_TESTING=FALSE`

**This step seems run good:**
-- The CXX compiler identification is GNU 7.5.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /share/data1/bio-soft/gcc-7.5.0/gcc-build-7.5/bin/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- bpp-core3 1.0.0 found:
--   static lib: not built/installed
--   shared lib: /data1/bio-soft/BioPP/bin/lib64/libbpp-core3.so.1.0.0
--   includes: /data1/bio-soft/BioPP/bin/include
-- bpp-seq3 1.0.0 found:
--   static lib: not built/installed
--   shared lib: /data1/bio-soft/BioPP/bin/lib64/libbpp-seq3.so.1.0.0
--   includes: /data1/bio-soft/BioPP/bin/include
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Configuring done
-- Generating done
-- Build files have been written to: /data1/bio-soft/BioPP/bpp-phyl-build

**Then make step:**
`make`

**Error occurred there:**
make: Warning: File 'Makefile' has modification time 26934 s in the future
make[1]: Warning: File 'CMakeFiles/Makefile2' has modification time 26938 s in the future
make[2]: Warning: File 'src/CMakeFiles/bpp-phyl3-shared.dir/flags.make' has modification time 26937 s in the future
make[2]: warning:  Clock skew detected.  Your build may be incomplete.
make[2]: Warning: File 'src/CMakeFiles/bpp-phyl3-shared.dir/flags.make' has modification time 26936 s in the future
[  0%] Building CXX object src/CMakeFiles/bpp-phyl3-shared.dir/Bpp/Phyl/App/PhylogeneticsApplicationTools.cpp.o
In file included from /data1/bio-soft/BioPP/bpp-phyl-master/src/Bpp/Phyl/App/PhylogeneticsApplicationTools.cpp:55:0:
/data1/bio-soft/BioPP/bpp-phyl-master/src/Bpp/Phyl/App/../Likelihood/NonHomogeneousSubstitutionProcess.h: In constructor 'bpp::NonHomogeneousSubstitutionProcess::NonHomogeneousSubstitutionProcess(std::shared_ptr<bpp::DiscreteDistribution>, bpp::ParametrizablePhyloTree*, bpp::FrequencySet*)':
/data1/bio-soft/BioPP/bpp-phyl-master/src/Bpp/Phyl/App/../Likelihood/NonHomogeneousSubstitutionProcess.h:165:39: error: use of deleted function 'bpp::AbstractSubstitutionProcess::AbstractSubstitutionProcess()'
     stationarity_(rootFreqs == nullptr)
                                       ^
In file included from /data1/bio-soft/BioPP/bpp-phyl-master/src/Bpp/Phyl/App/../Likelihood/SubstitutionProcessCollectionMember.h:45:0,
                 from /data1/bio-soft/BioPP/bpp-phyl-master/src/Bpp/Phyl/App/../Likelihood/SubstitutionProcessCollection.h:54,
                 from /data1/bio-soft/BioPP/bpp-phyl-master/src/Bpp/Phyl/App/../Likelihood/HmmProcessAlphabet.h:49,
                 from /data1/bio-soft/BioPP/bpp-phyl-master/src/Bpp/Phyl/App/../Likelihood/AutoCorrelationSequenceEvolution.h:45,
                 from /data1/bio-soft/BioPP/bpp-phyl-master/src/Bpp/Phyl/App/PhylogeneticsApplicationTools.cpp:52:
/data1/bio-soft/BioPP/bpp-phyl-master/src/Bpp/Phyl/App/../Likelihood/AbstractSubstitutionProcess.h:61:7: note: 'bpp::AbstractSubstitutionProcess::AbstractSubstitutionProcess()' is implicitly deleted because the default definition would be ill-formed:
 class AbstractSubstitutionProcess :
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/data1/bio-soft/BioPP/bpp-phyl-master/src/Bpp/Phyl/App/../Likelihood/AbstractSubstitutionProcess.h:61:7: error: no matching function for call to 'bpp::AbstractParameterAliasable::AbstractParameterAliasable()'
In file included from /data1/bio-soft/BioPP/bpp-phyl-master/src/Bpp/Phyl/App/../Io/../Model/FrequencySet/FrequencySet.h:50:0,
                 from /data1/bio-soft/BioPP/bpp-phyl-master/src/Bpp/Phyl/App/../Io/../Model/SubstitutionModel.h:46,
                 from /data1/bio-soft/BioPP/bpp-phyl-master/src/Bpp/Phyl/App/../Io/../Model/MixedTransitionModel.h:48,
                 from /data1/bio-soft/BioPP/bpp-phyl-master/src/Bpp/Phyl/App/../Io/BppOTransitionModelFormat.h:45,
                 from /data1/bio-soft/BioPP/bpp-phyl-master/src/Bpp/Phyl/App/../Io/BppOBranchModelFormat.h:45,
                 from /data1/bio-soft/BioPP/bpp-phyl-master/src/Bpp/Phyl/App/PhylogeneticsApplicationTools.cpp:42:
/data1/bio-soft/BioPP/bin/include/Bpp/Numeric/AbstractParameterAliasable.h:160:3: note: candidate: bpp::AbstractParameterAliasable::AbstractParameterAliasable(const bpp::AbstractParameterAliasable&)
   AbstractParameterAliasable(const AbstractParameterAliasable& ap);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~
/data1/bio-soft/BioPP/bin/include/Bpp/Numeric/AbstractParameterAliasable.h:160:3: note:   candidate expects 1 argument, 0 provided
/data1/bio-soft/BioPP/bin/include/Bpp/Numeric/AbstractParameterAliasable.h:154:3: note: candidate: bpp::AbstractParameterAliasable::AbstractParameterAliasable(const string&)
   AbstractParameterAliasable(const std::string& prefix) :
   ^~~~~~~~~~~~~~~~~~~~~~~~~~
/data1/bio-soft/BioPP/bin/include/Bpp/Numeric/AbstractParameterAliasable.h:154:3: note:   candidate expects 1 argument, 0 provided
make[2]: *** [src/CMakeFiles/bpp-phyl3-shared.dir/build.make:76: src/CMakeFiles/bpp-phyl3-shared.dir/Bpp/Phyl/App/PhylogeneticsApplicationTools.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:152: src/CMakeFiles/bpp-phyl3-shared.dir/all] Error 2
make: *** [Makefile:166: all] Error 2

Any suggestions to solve this problem ? Thanks~

Best,

Jiee.

**Comment by lgueguen** [comment]
Hello Jiee, 

it seems as if your compiler wants a default AbstractSubstitutionProcess construstor. I have added one in the latest version of bpp-phyl  on github. I let you try.

Cheers,
Laurent

**Comment by jiee1993** [comment]
Hi Laurent,

The problem is solved. Much thanks for your timely help.

Best,
Jiee
