### ISSUE TITLE
Offer: add LTT, nLTT and nLTT statistic

### ISSUE THREAD

**Issue by richelbilderbeek** [BioPP/bpp-phyl#5]
Dear Bio++,

For a scientific problem, me and my students developed classes `LTT` (lineages through time) and `nLTT` (normalized LTT) and unit tests, with the goal of using the nLTT statistic (from [1]) in C++.

I'd love to add this work to Bio++ and maintain it, if I have a go. 

Cheers, Richel Bilderbeek

## References

 * [1] Janzen, Thijs, Sebastian Höhna, and Rampal S. Etienne. "Approximate Bayesian computation of diversification rates from molecular phylogenies: introducing a new efficient summary statistic, the nLTT." Methods in Ecology and Evolution 6.5 (2015): 566-575. link
 * [2] Ibeh N., Aris-Brosou S. Estimation of sub-epidemic dynamics by means of Sequential Monte Carlo Approximate Bayesian Computation: an application to the Swiss HIV Cohort Study. bioRxiv (2016): 085993. link
 * [3] McCloskey, Rosemary M., Richard H. Liang, and Art FY Poon. Reconstructing contact network parameters from viral phylogenies. bioRxiv (2016): 050435. link
 * [4] Giardina, F., Romero-Severson, E. O., Albert, J., Britton, T., & Leitner, T. K. Inference of transmission network structure from HIV phylogenetic trees. bioRxiv (2016): 059865. link

**Comment by jydu** [comment]
Dear Richel,

This looks interesting! We'd be happy to consider a pull request.

J.

**Comment by richelbilderbeek** [comment]
Indeed, this got a bit outdated (as most of my work moved to R now). Thanks for closing :+1:
