### ISSUE TITLE
error: no matching function for call to ‘bpp::AbstractParameterAliasable::AbstractParameterAliasable()’

### ISSUE THREAD

**Issue by WU-WEIHONG** [BioPP/bpp-phyl#51]
Hi,

I have successfully compiled bpp-phyl program by cmake, but then I "make install" the program and generated the follow error:

(base) [wuwh@master bpp-phyl]$ make install
[  0%] Building CXX object src/CMakeFiles/bpp-phyl3-shared.dir/Bpp/Phyl/App/PhylogeneticsApplicationTools.cpp.o
In file included from /software/bio++/bpp-phyl/src/Bpp/Phyl/App/../Likelihood/SubstitutionProcessCollectionMember.h:45:0,
                 from /software/bio++/bpp-phyl/src/Bpp/Phyl/App/../Likelihood/SubstitutionProcessCollection.h:54,
                 from /software/bio++/bpp-phyl/src/Bpp/Phyl/App/../Likelihood/HmmProcessAlphabet.h:49,
                 from /software/bio++/bpp-phyl/src/Bpp/Phyl/App/../Likelihood/AutoCorrelationSequenceEvolution.h:45,
                 from /software/bio++/bpp-phyl/src/Bpp/Phyl/App/PhylogeneticsApplicationTools.cpp:52:
/software/bio++/bpp-phyl/src/Bpp/Phyl/App/../Likelihood/AbstractSubstitutionProcess.h: In constructor ‘bpp::AbstractSubstitutionProcess::AbstractSubstitutionProcess()’:
/software/bio++/bpp-phyl/src/Bpp/Phyl/App/../Likelihood/AbstractSubstitutionProcess.h:66:32: error: no matching function for call to ‘bpp::AbstractParameterAliasable::AbstractParameterAliasable()’
   AbstractSubstitutionProcess(){}
                                ^
In file included from /software/bio++/bpp-phyl/src/Bpp/Phyl/App/../Io/../Model/FrequencySet/FrequencySet.h:50:0,
                 from /software/bio++/bpp-phyl/src/Bpp/Phyl/App/../Io/../Model/SubstitutionModel.h:46,
                 from /software/bio++/bpp-phyl/src/Bpp/Phyl/App/../Io/../Model/MixedTransitionModel.h:48,
                 from /software/bio++/bpp-phyl/src/Bpp/Phyl/App/../Io/BppOTransitionModelFormat.h:45,
                 from /software/bio++/bpp-phyl/src/Bpp/Phyl/App/../Io/BppOBranchModelFormat.h:45,
                 from /software/bio++/bpp-phyl/src/Bpp/Phyl/App/PhylogeneticsApplicationTools.cpp:42:
/software/cmake-3.23.1/include/Bpp/Numeric/AbstractParameterAliasable.h:160:3: note: candidate: bpp::AbstractParameterAliasable::AbstractParameterAliasable(const bpp::AbstractParameterAliasable&)
   AbstractParameterAliasable(const AbstractParameterAliasable& ap);
   ^
/software/cmake-3.23.1/include/Bpp/Numeric/AbstractParameterAliasable.h:160:3: note:   candidate expects 1 argument, 0 provided
/software/cmake-3.23.1/include/Bpp/Numeric/AbstractParameterAliasable.h:154:3: note: candidate: bpp::AbstractParameterAliasable::AbstractParameterAliasable(const string&)
   AbstractParameterAliasable(const std::string& prefix) :
   ^
/software/cmake-3.23.1/include/Bpp/Numeric/AbstractParameterAliasable.h:154:3: note:   candidate expects 1 argument, 0 provided
make[2]: *** [src/CMakeFiles/bpp-phyl3-shared.dir/Bpp/Phyl/App/PhylogeneticsApplicationTools.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/bpp-phyl3-shared.dir/all] Error 2
make: *** [all] Error 2

It seems that the class defines a function with the same name as the library function?

Do you have any suggestions for fixing the error? 

Many thanks

Best wishes,

Wu

**Comment by lgueguen** [comment]
Hi Wu,

sorry for my late reply (I missed your message).

It seems that your compiler wants a default constructor for AbstractParameterAliasable from which AbstractSubstitutionProcess inherits. Thinking of it, it is fair, it is rather surprising that in compiled with our compilers.

Can you try replacing, in src/bpp-phyl/src/Bpp/Phyl/Likelihood/AbstractSubstitutionProcess.h, at line 69, 

  AbstractSubstitutionProcess() {}

with:

  AbstractSubstitutionProcess() :
    AbstractParameterAliasable("")
  {}


Let me know if it works,
cheers,
Laurent
