### ISSUE TITLE
Bpp/Phyl/Io/ExtendedNewick.cpp :: missing file 

### ISSUE THREAD

**Issue by EricDeveaud** [BioPP/bpp-phyl#55]
Hello fresh git clone of https://github.com/BioPP/bpp-phyl 

```
git rev-parse --short HEAD
da6bf9a2
```

when trying to build bpp-phyl I have the following error 

```
CMake Error at src/CMakeLists.txt:280 (add_library):
  Cannot find source file:

    Bpp/Phyl/Io/ExtendedNewick.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm
  .ccm .cxxm .c++m .h .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90
  .f95 .f03 .hip .ispc


CMake Error at src/CMakeLists.txt:280 (add_library):
  No SOURCES given to target: bpp-phyl3-shared
```

regards

Eric

**Comment by DininduSenanayake** [comment]
I can reproduce this error as well. There was a similar error for another source reported in https://github.com/BioPP/bpp-phyl/issues/52 but the resolution doesn't have the commit id to see what exactly was the fix  😞

**Comment by jydu** [comment]
Looks like a new file forgot to be added to the repository... @lgueguen ?

**Comment by lgueguen** [comment]
Hi, 

yes indeed, sorry.
It is fixed.

Laurent
